name: API Feature suggest
description: Suggest a new API feature
title: '[Feature]: '
body:
  - type: dropdown
    id: type
    attributes:
      label: Feature Type
      description: What's the type of the feature
      options:
        - Block
        - Item
        - Entity
        - World
        - Other (please write it in additional info)
    validations:
      required: true
  - type: textarea
    id: describe
    attributes:
      label: Describe the feature
      description: What's the feature of the usage and what it can do?
      placeholder: All in title
    validations:
      required: true
  - type: textarea
    id: additional-info
    attributes:
      label: Additional Info
  - type: checkboxes
    id: checks
    attributes:
      label: Checks
      options:
        - label: I confirm that this issue has not been raised before
          required: true
        - label: I confirm that this feature has not been implemented before
          required: true